### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by nickforddesign** [zspecza/common-tags#202]
I can't seem to find any TS types for this library, any chance of adding them?

**Comment by fatfisz** [comment]
Oh, I actually forgot that this package is in for a nice TS rewrite. Can't promise when this will be done (now that I remember about it, you can expect it sooner rather than later). Until then you can use @types/common-tags, at least for the older version.

**Comment by fatfisz** [comment]
I'm closing this since I've created #204 which should take care of it.
